name: CI
on: [push, pull_request]
env:
  UI_VERSION: ${{ github.sha }}
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base:v2.0.0
    steps:
      - uses: actions/checkout@v3

      # Install Node 16
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: "npm"

      - run: npm install -g npm@8.5.5

      # Install & build:
      - run: npm ci

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*
          if-no-files-found: error

  publish-pages:
    name: Publish Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
